name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Hugo
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: copy file via ssh password
      uses: horochx/deploy-via-scp@master
      with:
        local: public
        remote: /var/www/html/homepage
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}