name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Hugo
      uses: lowply/build-hugo@v0.74.3
    - name: copy file via ssh password
      uses: horochx/deploy-via-scp@master
      with:
        local: public
        remote: /var/www/html/homepage
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}